# Generated by Django 6.0.3 on 2026-03-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media_assets/'),
        ),
    ]
