# Generated by Django 6.0.3 on 2026-03-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_mediaasset_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='primary_image_upload',
            field=models.FileField(blank=True, null=True, upload_to='pages/primary_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_upload',
            field=models.FileField(blank=True, null=True, upload_to='posts/cover_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_image_upload',
            field=models.FileField(blank=True, null=True, upload_to='posts/primary_images/'),
        ),
    ]
