# Generated by Django 6.0.3 on 2026-03-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_page_primary_image_upload_post_cover_image_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blocks_json',
            field=models.JSONField(blank=True, help_text='Block-based content in JSON format', null=True),
        ),
    ]
