# Generated by Django 6.0.3 on 2026-03-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_post_blocks_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='set_homepage',
            field=models.BooleanField(default=False, help_text='Set this page as the homepage. Only one page can be the homepage at a time.'),
        ),
    ]
