# Generated by Django 6.0.3 on 2026-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_page_set_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_title_display',
            field=models.BooleanField(default=True, help_text='Display the page title on the frontend. When disabled, the title will not be shown.'),
        ),
    ]
